### ISSUE TITLE
Using a target size (torch.Size([16, 1, 64, 64])) that is different to the input size (torch.Size([15, 1, 64, 64])) is deprecated. Please ensure they have the same size.

### ISSUE THREAD

**Issue by bdlneto** [TobiasSunderdiek/cartoon-gan#6] opened 2021-11-25 20:21 UTC
Hi again, @TobiasSunderdiek 

During the trainning process, this error raised and I have no Idea of what is causing it. I am using the default dataset (safebooru) and default params for the trainning.

Do you have any idea on how to fix it?

Regards

**Comment by TobiasSunderdiek** [comment] 2021-11-26 21:10
Hi @bdlneto,

thanks again for the issue, every issue makes this repo better!

I think this is caused by processing a batch smaller than 16. Does this error occur while processing the training cell in the notebook?

At some places in the code the `actual_batch_size` is used to avoid this, but it seems I missed another place.

I think during the download of the images, some error occured. Can you please check if all images in the `cartoons/`, `cartoons_smoothed/` and `photos/` folder contain the same amount of 4000 images?

Thanks and best regards!

**Comment by bdlneto** [comment] 2021-11-29 14:43
Hi!

I also found it to be some problem during the download process.

I'll check the folders and, if necessary, re-download them

Thanks again!

**Comment by TobiasSunderdiek** [comment] 2022-01-12 10:52
Great, thank you for helping me making this repo better by having opened this issue!

I'll close it now, best regards

**Closed as completed by TobiasSunderdiek** 2022-01-12 10:52 UTC
